build-app:
  stage: build
  except:
    - master
  image: ghcr.io/cirruslabs/flutter:latest
  script:
    - cd lib
    - flutter pub get
    - flutter packages pub run build_runner build
    - flutter test --coverage
  artifacts:
    paths:
      - coverage/
  coverage: '/^TOTAL\s+\|\s+(\d+\.\d+)/'