# build.yaml
# File: build.yaml
targets:
  $default:
    builders:
      flutter_form_bricks|auto_form_schema:
        generate_for:
          - lib/**.dart

builders:
  auto_form_schema:
    import: "package:flutter_form_bricks/builders.dart"
    builder_factories: ["autoFormSchema"]
    build_extensions: {".dart": ["_schema.g.dart"]}
    auto_apply: dependents
    build_to: source
